Refactoring of variables names, function names, magic numbers and if statements
fga-verival/2020-2Grupo4 pull request #4
Opened 2021-04-20 22:18 UTC by fmaachadoo

2021-04-21 23:39 UTC, Gustavo-Nogueira commented
@fmaachadoo, além do conflito, ficou faltando adicionar a parte do cálculo de rendimento líquido(testes e implementação).

2021-04-21 23:44 UTC, Gustavo-Nogueira requested changes
@fmaachadoo, além do conflito, ficou faltando adicionar a parte do cálculo de rendimento líquido(testes e implementação).

2021-04-26 04:44 UTC, Gustavo-Nogueira commented
Corrigi o problema que estava gerando aquela falha no segundo caso de teste da renda líquida. A falha era causa por um bug no método que calcula da alíquota de imposto.

2021-04-26 04:45 UTC, Gustavo-Nogueira approved these changes
Testado e aprovado !

2021-04-26 18:47 UTC, ErickGiffoni commented
> Testado e aprovado !

Booooaaaaaa

2021-04-26 18:50 UTC, ErickGiffoni approved these changes
topen

2021-04-26 18:50 UTC, merged